name: Magic KPI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      DEVICEKPIBLOB: ${{ secrets.DEVICEKPIBLOB }}
      GRAPH_APPSECRET: ${{ secrets.GRAPH_APPSECRET }}
      APPCLIENT_SECRET: ${{ secrets.APPCLIENT_SECRET }}

      GRAPH_APPID: ${{ vars.GRAPH_APPID }}
      GRAPH_APPDOMAIN: ${{ vars.GRAPH_APPDOMAIN }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      APPCLIENT_ID: ${{ vars.APPCLIENT_ID }}
      APPCLIENT_DOMAIN: ${{ vars.APPCLIENT_DOMAIN }}
      SITEURL: ${{ vars.SITEURL }}
      AADDOMAIN: ${{ vars.AADDOMAIN }}
      MAILTO: ${{ vars.MAILTO }}
      MAILFROM: ${{ vars.MAILFROM }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: KPI Data
        run: pwsh "./00/kpi/run.ps1"
        shell: pwsh
